//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwinSovet.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwinSovet.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жители.
        /// </summary>
        public static string Aborigens {
            get {
                return ResourceManager.GetString("Aborigens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск жителей.
        /// </summary>
        public static string AborigenSearch {
            get {
                return ResourceManager.GetString("AborigenSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор жителей.
        /// </summary>
        public static string AborigensSelection {
            get {
                return ResourceManager.GetString("AborigensSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twin Sovet.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадь.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Документы.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выделить квартиры без хозяина.
        /// </summary>
        public static string DoHighlightFlatsWithoutOwner {
            get {
                return ResourceManager.GetString("DoHighlightFlatsWithoutOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квартира.
        /// </summary>
        public static string Flat {
            get {
                return ResourceManager.GetString("Flat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этаж.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан.
        /// </summary>
        public static string He_IsNotDefined {
            get {
                return ResourceManager.GetString("He_IsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больничная.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показания.
        /// </summary>
        public static string Indications {
            get {
                return ResourceManager.GetString("Indications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загружаем список жителей.
        /// </summary>
        public static string LoadingAborigensList {
            get {
                return ResourceManager.GetString("LoadingAborigensList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мужичок.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мебельная.
        /// </summary>
        public static string Mebelnaya {
            get {
                return ResourceManager.GetString("Mebelnaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заметки.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string Otchestvo {
            get {
                return ResourceManager.GetString("Otchestvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Владелец.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотографии.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to План дома.
        /// </summary>
        public static string PlanOfHouse {
            get {
                return ResourceManager.GetString("PlanOfHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по квартирам.
        /// </summary>
        public static string SearchByFlats {
            get {
                return ResourceManager.GetString("SearchByFlats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по этажам.
        /// </summary>
        public static string SearchByFloors {
            get {
                return ResourceManager.GetString("SearchByFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Секция.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать существующего.
        /// </summary>
        public static string SelectExisting_He {
            get {
                return ResourceManager.GetString("SelectExisting_He", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указана.
        /// </summary>
        public static string She_IsNotDefined {
            get {
                return ResourceManager.GetString("She_IsNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принять.
        /// </summary>
        public static string ToDoAccept {
            get {
                return ResourceManager.GetString("ToDoAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string ToDoAdd {
            get {
                return ResourceManager.GetString("ToDoAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистить.
        /// </summary>
        public static string ToDoClear {
            get {
                return ResourceManager.GetString("ToDoClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернуть все.
        /// </summary>
        public static string ToDoCollapseAll {
            get {
                return ResourceManager.GetString("ToDoCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свернуть все этажи.
        /// </summary>
        public static string ToDoCollapseAllFloors {
            get {
                return ResourceManager.GetString("ToDoCollapseAllFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать собственника.
        /// </summary>
        public static string ToDoCreateOwner {
            get {
                return ResourceManager.GetString("ToDoCreateOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string ToDoEdit {
            get {
                return ResourceManager.GetString("ToDoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть все.
        /// </summary>
        public static string ToDoExpandAll {
            get {
                return ResourceManager.GetString("ToDoExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развернуть все этажи.
        /// </summary>
        public static string ToDoExpandAllFloors {
            get {
                return ResourceManager.GetString("ToDoExpandAllFloors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string ToDoSave {
            get {
                return ResourceManager.GetString("ToDoSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string ToDoSelect {
            get {
                return ResourceManager.GetString("ToDoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать визитку жителя.
        /// </summary>
        public static string ToDoShowAborigenCard {
            get {
                return ResourceManager.GetString("ToDoShowAborigenCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать заметки.
        /// </summary>
        public static string ToDoShowNotes {
            get {
                return ResourceManager.GetString("ToDoShowNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать фотографии.
        /// </summary>
        public static string ToDoShowPhotos {
            get {
                return ResourceManager.GetString("ToDoShowPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to УК.
        /// </summary>
        public static string UK_short {
            get {
                return ResourceManager.GetString("UK_short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узреть историю показаний.
        /// </summary>
        public static string ViewIndicationsHistory {
            get {
                return ResourceManager.GetString("ViewIndicationsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дама.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
    }
}
